#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.chef.io/api/v1'

cookbook 'apt', '~> 2.7'
cookbook 'git', '~> 4.3'
cookbook 'nginx', '~> 2.7'
cookbook 'php', '~> 1.7'
cookbook 'composer', '~> 2.1'
cookbook 'mysql', '~> 6.1'
cookbook 'mysql2_chef_gem', '~> 1.0'
cookbook 'database', '~> 4.0'
cookbook 'nodejs', '~> 2.4'
cookbook 'zsh', '~> 1.0'
cookbook 'redis2', '~> 0.5'
cookbook 'blackfire', '~> 2.0'
cookbook 'mongodb', '~> 0.16'
