#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'openssl'
cookbook 'apache2'
cookbook 'memcached'
cookbook 'php'
cookbook 'composer'
cookbook 'mysql'
cookbook 'database'
cookbook 'nodejs'
cookbook 'zsh'
cookbook 'rvm'
cookbook 'redis2'
cookbook 'blackfire'
